metric: COCO
num_classes: 3

TrainDataset:
  !COCODataSet
    image_dir: images
    anno_path: COCO/train.json
    dataset_dir: /home/zhaohj/Documents/dataset/Kaggle/sartorius-cell-instance-segmentation
    data_fields: ['image', 'gt_bbox', 'gt_class', 'gt_poly', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: images
    anno_path: COCO/val.json
    dataset_dir: /home/zhaohj/Documents/dataset/Kaggle/sartorius-cell-instance-segmentation

TestDataset:
  !ImageFolder
    anno_path: COCO/val.json
